theme: minima
title: Alule Robert
author: Alule Robert
email: contact@alulerobert.me
description: >-
  MSc Biochemistry Student & Educator. Researching Host-Pathogen Interactions,
  Systems Biology, and Malaria in Uganda. Skilled in Python, R, and Biological Data Analysis.
show_excerpts: false

# Social settings (These add icons to your footer)
github_username: robertalule
twitter_username:  AluleRobert
linkedin_username: AluleRobert
email: contact@alulerobert.me
