theme: minima
title: Alule Robert
author: Alule Robert
email: contact@alulerobert.me
description: >-
  MSc Biochemistry student and biological sciences educator.
  Research interests include Hostâ€“pathogen interactions, Systems biology, Neglected Tropical Pathogens.
  Experience with Python, R, and biological data analysis.
show_excerpts: true

# Social settings (These add icons to your footer)
github_username: robertalule
twitter_username:  AluleRobert
linkedin_username: AluleRobert

minima:
  skin: classic
header_pages:
  - index.md
  - research.md
  - projects.md
